# Generated by Django 5.2.13 on 2026-07-09 06:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(max_length=200, unique=True)),
                ('asset_number', models.CharField(max_length=100, unique=True)),
                ('office_version', models.CharField(blank=True, max_length=100)),
                ('email_license_status', models.CharField(blank=True, max_length=100)),
                ('user_pc', models.CharField(blank=True, max_length=200)),
                ('acquisition_date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('vendor_contract_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('maintenance', 'Perbaikan'), ('decommissioned', 'Dihapus')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'locations',
                'ordering': ['name'],
            },
        ),
    ]
