# Generated by Django 5.2.13 on 2026-07-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=200)),
                ('office_type', models.CharField(blank=True, max_length=100)),
                ('email_license', models.EmailField(blank=True, db_index=True, max_length=200)),
                ('asset_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('box_number', models.CharField(blank=True, max_length=100)),
                ('user_name', models.CharField(blank=True, db_index=True, max_length=300)),
                ('activation_date', models.CharField(blank=True, max_length=50)),
                ('mac_address', models.CharField(blank=True, max_length=100)),
                ('vendor_provider', models.CharField(blank=True, db_index=True, max_length=200)),
                ('pdf_report_certificate', models.CharField(blank=True, max_length=200)),
                ('pnbp_status', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='notebook_docs/')),
                ('notes', models.TextField(blank=True)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Tidak Aktif')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notebook_leases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('sub_class', models.CharField(db_index=True, max_length=150)),
                ('operating_system', models.CharField(blank=True, max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=150)),
                ('serial_number', models.CharField(max_length=150, unique=True)),
                ('owner', models.CharField(db_index=True, max_length=200)),
                ('location', models.CharField(db_index=True, max_length=200)),
                ('asset_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('confidentiality', models.SmallIntegerField(blank=True, null=True)),
                ('integrity', models.SmallIntegerField(blank=True, null=True)),
                ('availability', models.SmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'physical_assets',
                'ordering': ['asset_name'],
                'indexes': [models.Index(fields=['serial_number'], name='physical_as_serial__90b1d1_idx'), models.Index(fields=['asset_number'], name='physical_as_asset_n_f30595_idx')],
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('license_type', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=300)),
                ('license_number', models.CharField(blank=True, max_length=500)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('location_install', models.CharField(blank=True, max_length=300)),
                ('room_location', models.CharField(blank=True, max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'software_licenses',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['license_type'], name='software_li_license_c4ddd0_idx'), models.Index(fields=['vendor'], name='software_li_vendor_47acde_idx'), models.Index(fields=['status'], name='software_li_status_14d64f_idx')],
            },
        ),
    ]
