# Generated by Django 5.2.13 on 2026-07-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notebooklease_physicalasset_softwarelicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebooklease',
            name='asset_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='physicalasset',
            name='asset_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
