# Generated by Django 5.2.13 on 2026-07-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_notebooklease_asset_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebooklease',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='physicalasset',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
