# Generated by Django 5.2.13 on 2026-07-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_notebooklease_serial_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('ip_address', models.CharField(blank=True, max_length=100)),
                ('sub_class', models.CharField(db_index=True, max_length=150)),
                ('owner', models.CharField(db_index=True, max_length=200)),
                ('location', models.CharField(db_index=True, max_length=200)),
                ('confidentiality', models.SmallIntegerField(blank=True, null=True)),
                ('integrity', models.SmallIntegerField(blank=True, null=True)),
                ('availability', models.SmallIntegerField(blank=True, null=True)),
                ('value', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'software_applications',
                'ordering': ['asset_name'],
            },
        ),
    ]
