# Generated by Django 5.2.13 on 2026-07-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_softwareapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebooklease',
            name='import_month',
            field=models.CharField(db_index=True, default='2026-07', max_length=7),
        ),
        migrations.AddField(
            model_name='physicalasset',
            name='import_month',
            field=models.CharField(db_index=True, default='2026-07', max_length=7),
        ),
        migrations.AddField(
            model_name='softwareapplication',
            name='import_month',
            field=models.CharField(db_index=True, default='2026-07', max_length=7),
        ),
        migrations.AddField(
            model_name='softwarelicense',
            name='import_month',
            field=models.CharField(db_index=True, default='2026-07', max_length=7),
        ),
        migrations.AddIndex(
            model_name='notebooklease',
            index=models.Index(fields=['import_month'], name='notebook_le_import__4c9222_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalasset',
            index=models.Index(fields=['import_month'], name='physical_as_import__f0ed27_idx'),
        ),
        migrations.AddIndex(
            model_name='softwareapplication',
            index=models.Index(fields=['import_month'], name='software_ap_import__21f2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='softwarelicense',
            index=models.Index(fields=['import_month'], name='software_li_import__ae066c_idx'),
        ),
    ]
