# Generated by Django 5.2.13 on 2026-07-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notebooklease_import_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebooklease',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='asset_images/'),
        ),
        migrations.AddField(
            model_name='physicalasset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='asset_images/'),
        ),
    ]
