# Generated by Django 5.2.13 on 2026-07-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_image_field_to_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebooklease',
            name='technical_specs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='physicalasset',
            name='technical_specs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
